services:
  my_website:
    image: dubhar/asciidocsite:latest
    ports:
      - "80:80"
    environment:
      - "REPO=git@github.com:Dubhar/my_website.git"
    volumes:
      - "./MyWebsite/id_rsa:/ssh_key:ro"
    restart: unless-stopped
